{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common-ktx",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "7250267"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.3.5.aar",
          "url": "navigation-common-ktx-2.3.5.aar",
          "size": 26400,
          "sha512": "703f0bd512c0c1094f4c20a54ba094291639912b5f506f16c20236cfd794c83b6bf593f8727b6f27087aea3a28c6c7a4615d671a183130b51e8c141af9b90cc8",
          "sha256": "ea75e05f355a2d649e8b985e19f1dd313e4a13cb03b7e5b8471ff59f24f7787e",
          "sha1": "508ce0e03d822ac25274cd8b70d39d1eed7c27c2",
          "md5": "71b06ce5d28df00385145c4987a476b3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.3.5.aar",
          "url": "navigation-common-ktx-2.3.5.aar",
          "size": 26400,
          "sha512": "703f0bd512c0c1094f4c20a54ba094291639912b5f506f16c20236cfd794c83b6bf593f8727b6f27087aea3a28c6c7a4615d671a183130b51e8c141af9b90cc8",
          "sha256": "ea75e05f355a2d649e8b985e19f1dd313e4a13cb03b7e5b8471ff59f24f7787e",
          "sha1": "508ce0e03d822ac25274cd8b70d39d1eed7c27c2",
          "md5": "71b06ce5d28df00385145c4987a476b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-ktx-2.3.5-sources.jar",
          "url": "navigation-common-ktx-2.3.5-sources.jar",
          "size": 9270,
          "sha512": "2e660b763af1be2ce6c7a11a357707f4b2661e1d087d7cd0f5b7d3ea35d274ed1e7be631eef53f23c25dac96233c22a2b88f801d44d276d15f50fe873cc9f0bb",
          "sha256": "3785b406ae010b5b2080a61ac30f34473414c7b49bd07f0c0ade32ab204c931a",
          "sha1": "1a3ce7c2b9dcc97c1d25ef6ab8e016b5a76de983",
          "md5": "7a3b42155cd6aca62a286819294a8545"
        }
      ]
    }
  ]
}
