{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime-ktx",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "7250267"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.3.5.aar",
          "url": "navigation-runtime-ktx-2.3.5.aar",
          "size": 13228,
          "sha512": "4dc983e4d7d7172af7d7a39314b206dcf8e39d1f63e0358b9c635a035a9e3490f6f80a1639ed192ac1d41e33eeda46378873a7eec61dc4731004a15acc9bfa12",
          "sha256": "a44fc52231a67d6afe7b8891d272507febddbd922e7b231c8bd36720b94a042b",
          "sha1": "47c77268f09987c46e20bd310afde51493fffba3",
          "md5": "42ea2fc259c7404afabd5a5ef9d9be48"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.3.5.aar",
          "url": "navigation-runtime-ktx-2.3.5.aar",
          "size": 13228,
          "sha512": "4dc983e4d7d7172af7d7a39314b206dcf8e39d1f63e0358b9c635a035a9e3490f6f80a1639ed192ac1d41e33eeda46378873a7eec61dc4731004a15acc9bfa12",
          "sha256": "a44fc52231a67d6afe7b8891d272507febddbd922e7b231c8bd36720b94a042b",
          "sha1": "47c77268f09987c46e20bd310afde51493fffba3",
          "md5": "42ea2fc259c7404afabd5a5ef9d9be48"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-ktx-2.3.5-sources.jar",
          "url": "navigation-runtime-ktx-2.3.5-sources.jar",
          "size": 6128,
          "sha512": "f976814e20f825b4f16bf017c59918c3eb42304e8cb934b491431d2cf1e280bceea3a63b255a8ebbfcbb3886fdf26bd2a258e41928747b90eb04075e421ef4df",
          "sha256": "17df0a9cfd3b645ce58d9716f293ffdcfd8f30b60b87dab2a3cf099dddc1e70a",
          "sha1": "4d2da12a557444e5706dd6ca99f059ec099a45de",
          "md5": "fe0b36da8a72a76b3f3e34d30eebbcb2"
        }
      ]
    }
  ]
}
