{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui-ktx",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "7250267"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.3.5.aar",
          "url": "navigation-ui-ktx-2.3.5.aar",
          "size": 32272,
          "sha512": "80fd26e07fa8e02fe390a0ec3c8f44f97301a5bd9b249a91c028c3009d806650b9db60385ffc49bf7da30b2bc9598512fe0d03ae18253f6b2a4a5a00755a4f33",
          "sha256": "f5a1fc4f47f1b3d6cf14284c1f9f4207804cdefac215e046f879c9a2f7bc005b",
          "sha1": "3b701ccd9f0720787987472de8b04070baf2a704",
          "md5": "ab05ffd5b7473e82a91aeebe4678a95e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.3.5.aar",
          "url": "navigation-ui-ktx-2.3.5.aar",
          "size": 32272,
          "sha512": "80fd26e07fa8e02fe390a0ec3c8f44f97301a5bd9b249a91c028c3009d806650b9db60385ffc49bf7da30b2bc9598512fe0d03ae18253f6b2a4a5a00755a4f33",
          "sha256": "f5a1fc4f47f1b3d6cf14284c1f9f4207804cdefac215e046f879c9a2f7bc005b",
          "sha1": "3b701ccd9f0720787987472de8b04070baf2a704",
          "md5": "ab05ffd5b7473e82a91aeebe4678a95e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-ktx-2.3.5-sources.jar",
          "url": "navigation-ui-ktx-2.3.5-sources.jar",
          "size": 8751,
          "sha512": "0d56d35c76ca24964807607764080077f0d8ce960dc61e14629a2a1d50bd424ab455be041d64dc17edc52511c0db4d25c3e7b359a5bb44c9c37f2e0934ea1685",
          "sha256": "dc293a071dc2f04f69d456de6734531fa52ae69fecc83a4e1812006a3e5e3eae",
          "sha1": "407dd936012d5b65b0af3e897ea62e436a811419",
          "md5": "e5ff0652316f70fa6f7263ce5094a7ba"
        }
      ]
    }
  ]
}
