{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat-resources",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7546299"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.3.1.aar",
          "url": "appcompat-resources-1.3.1.aar",
          "size": 65246,
          "sha512": "3e068720c69cd0f90cc61d2442ff25bc96f7cc62ec5675e08963b8cbade8b10b9b6c3c8d40dad6ba594c43ebc0b9ef49d3c1ad5ff5719cca1171c1f8ad358a8d",
          "sha256": "e3306cd3e9a19a28a5de5ec3b379580f237c4d81c15c3d795404be9291890a75",
          "sha1": "32ad26fa0a18f5df7c7bff16aeaa1ecfef593877",
          "md5": "2e3e3f4ce71be50f4e95ac89dcf287c0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.3.1.aar",
          "url": "appcompat-resources-1.3.1.aar",
          "size": 65246,
          "sha512": "3e068720c69cd0f90cc61d2442ff25bc96f7cc62ec5675e08963b8cbade8b10b9b6c3c8d40dad6ba594c43ebc0b9ef49d3c1ad5ff5719cca1171c1f8ad358a8d",
          "sha256": "e3306cd3e9a19a28a5de5ec3b379580f237c4d81c15c3d795404be9291890a75",
          "sha1": "32ad26fa0a18f5df7c7bff16aeaa1ecfef593877",
          "md5": "2e3e3f4ce71be50f4e95ac89dcf287c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appcompat-resources-1.3.1-sources.jar",
          "url": "appcompat-resources-1.3.1-sources.jar",
          "size": 39771,
          "sha512": "74468531b69f9c0ae550a7e84def80d98d2de325c6ed36043a50ea8c090f94045901823c256c3ec31dcf68d01e5e92e73fe57066def2330eb2e89c214826914d",
          "sha256": "26455b2dbdbd4326c5ad406960005e48dcdb7fc495b0a3a22aa3a703a18ed302",
          "sha1": "fa1169a9b404f7e905756330af6d13e27dcee50e",
          "md5": "b8ebde19acd29c203a88d334c5d629b4"
        }
      ]
    }
  ]
}
