{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.savedstate",
    "module": "savedstate",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7101960"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-1.1.0.aar",
          "url": "savedstate-1.1.0.aar",
          "size": 11201,
          "sha512": "62911d0c92cf236b328c2a71fa43d4d479791849696c9da2251cb94706ead45c31ecf2adae9446315de6939297ee85052c3e43d441c96c3a6643461ed7b0ead2",
          "sha256": "d60bbe44c2c08083a17c5dc678a6d6b4d0a2d664858016ab5c049cbea90a63b7",
          "sha1": "8d4785f699f93e4020b185e2b7de37cb1f58753c",
          "md5": "eab7e98eb0e7c372f5f584986f50c4a3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-1.1.0.aar",
          "url": "savedstate-1.1.0.aar",
          "size": 11201,
          "sha512": "62911d0c92cf236b328c2a71fa43d4d479791849696c9da2251cb94706ead45c31ecf2adae9446315de6939297ee85052c3e43d441c96c3a6643461ed7b0ead2",
          "sha256": "d60bbe44c2c08083a17c5dc678a6d6b4d0a2d664858016ab5c049cbea90a63b7",
          "sha1": "8d4785f699f93e4020b185e2b7de37cb1f58753c",
          "md5": "eab7e98eb0e7c372f5f584986f50c4a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "savedstate-1.1.0-sources.jar",
          "url": "savedstate-1.1.0-sources.jar",
          "size": 8564,
          "sha512": "6f3a05df6886aae59fdbd8ad4bb4c207419cee97401a848726c7698d038c123cf39b8f15bfd1eef7ba5ed3ea0c16b200b305b5ba6106cf957cf77405cc2f4985",
          "sha256": "17a5307db49192c506456ece77352c58c621ec35a280ebad3ecbe2d5dd586df3",
          "sha1": "073464c2c55129727354a95ffa91dc9c2cf0c78b",
          "md5": "fc3f8c39a1ebe510256d9e62669e9774"
        }
      ]
    }
  ]
}
