{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7514997"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.2.4.aar",
          "url": "activity-1.2.4.aar",
          "size": 69550,
          "sha512": "1045aba9e8434c7aa63625d260dd4d786dc8386eb7aab8a93340d53bee5130ed0533d24bbe613bd8e48dbbb78cd74f65ff192d9320405b170afbbdd0dfa983ff",
          "sha256": "ae8e9c7de57e387d2ad90e73f3a5a5dfd502bd4f034c1dccfdb3506d1d2df81a",
          "sha1": "bebd083d1486ed7f033b2dcc06e7cdefede4445f",
          "md5": "5d8345995e345cec43a6ea2897f4251e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.2.4.aar",
          "url": "activity-1.2.4.aar",
          "size": 69550,
          "sha512": "1045aba9e8434c7aa63625d260dd4d786dc8386eb7aab8a93340d53bee5130ed0533d24bbe613bd8e48dbbb78cd74f65ff192d9320405b170afbbdd0dfa983ff",
          "sha256": "ae8e9c7de57e387d2ad90e73f3a5a5dfd502bd4f034c1dccfdb3506d1d2df81a",
          "sha1": "bebd083d1486ed7f033b2dcc06e7cdefede4445f",
          "md5": "5d8345995e345cec43a6ea2897f4251e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.2.4-sources.jar",
          "url": "activity-1.2.4-sources.jar",
          "size": 35948,
          "sha512": "66efa514af5e9639c521005a4b171dcf03dafb13c43298659a685d38f26f682d40639f42067a6860a9ce50d90792e86e06f90c7d270a3669ddc1af80f21b53d2",
          "sha256": "6ac2dcd6a9e90456ae0833a0a7fd6f9aa6e124dbb50f215b4c63c1b43b0ea280",
          "sha1": "2572345ff3e71e4e97140b01423cb80765b5b3e5",
          "md5": "7e09ef1148b37eb1fb7796445b160368"
        }
      ]
    }
  ]
}
