{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core-ktx",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7201951"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.3.1.aar",
          "url": "lifecycle-livedata-core-ktx-2.3.1.aar",
          "size": 14540,
          "sha512": "7815790b70feacecbb096b53a0d81689b2886bb61190baef6b528dbedb09a8fbf5afc1ddd1263d56c7e54c3f1284bc3fae7fcb53c1f80d5bc7bd6a0967e1e253",
          "sha256": "6dd41c3c33daeb503fd87fbfff7043adb0be6c541a9c9e09bf531ca49520fddb",
          "sha1": "63db48d3911ca7af98f1f4ba6fbf5f7f51d4b43a",
          "md5": "7fde8868b2d792f2f1d5777a49bfc314"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.3.1.aar",
          "url": "lifecycle-livedata-core-ktx-2.3.1.aar",
          "size": 14540,
          "sha512": "7815790b70feacecbb096b53a0d81689b2886bb61190baef6b528dbedb09a8fbf5afc1ddd1263d56c7e54c3f1284bc3fae7fcb53c1f80d5bc7bd6a0967e1e253",
          "sha256": "6dd41c3c33daeb503fd87fbfff7043adb0be6c541a9c9e09bf531ca49520fddb",
          "sha1": "63db48d3911ca7af98f1f4ba6fbf5f7f51d4b43a",
          "md5": "7fde8868b2d792f2f1d5777a49bfc314"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.3.1-sources.jar",
          "url": "lifecycle-livedata-core-ktx-2.3.1-sources.jar",
          "size": 1631,
          "sha512": "aec27370748b879276405755e63a377e08307bfe2f370687ee18fa5c43cb5e203fe5e3bcc9cda40390c872bf279e96bc2bae2f0a9e2ee631f861b2ad0e54c0ae",
          "sha256": "b7a2a7c66a58440b0ba30c68abe17074836f217123fb6ea728279834641a7c77",
          "sha1": "0ec507705520b7ddccce7da52bbf5abd9ecd1808",
          "md5": "c552138cfc58a3f4d73c8acbb66e4a86"
        }
      ]
    }
  ]
}
