{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7546299"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-1.3.1.aar",
          "url": "appcompat-1.3.1.aar",
          "size": 1084067,
          "sha512": "7b6f872b0b809efb2cbc1371dd3b61a8c7ea14446297370a558876139a18f035bab00587979c475e51f05740d780f2d9223838a66969e29d59f6264e5f3cb596",
          "sha256": "959b1daefe40d5e7eed1022f97730b22bc5fd52e6a6083eba284fa86c2971303",
          "sha1": "b9bc6aeb85e9bd2bc7ce829960b07d47eda7a1a9",
          "md5": "19cb8c81e85229a2d43fc770278b7dbe"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-1.3.1.aar",
          "url": "appcompat-1.3.1.aar",
          "size": 1084067,
          "sha512": "7b6f872b0b809efb2cbc1371dd3b61a8c7ea14446297370a558876139a18f035bab00587979c475e51f05740d780f2d9223838a66969e29d59f6264e5f3cb596",
          "sha256": "959b1daefe40d5e7eed1022f97730b22bc5fd52e6a6083eba284fa86c2971303",
          "sha1": "b9bc6aeb85e9bd2bc7ce829960b07d47eda7a1a9",
          "md5": "19cb8c81e85229a2d43fc770278b7dbe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appcompat-1.3.1-sources.jar",
          "url": "appcompat-1.3.1-sources.jar",
          "size": 462613,
          "sha512": "c1eb48bcedfd694657af0bf7f7167e5c7e2ea0648dbe0bbfc048b49e6eebc7c5f977a67f1d90d9bcc8662f601c8caa0b4ad2bdde6c8981bb3a48ad8b418be3f4",
          "sha256": "bc2ec38cc39dad147d7450c58dc89cd2683438e8de9d98c317e93a51a18d1e65",
          "sha1": "45a346a05e7ff27a01c59452379c5939cbb53c03",
          "md5": "1d2545cf733d38bc3de0485a049393ae"
        }
      ]
    }
  ]
}
